version: 2
jobs:
  lint:
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build image from Dockerfile
          command: docker build . --tag=blockade-api --build-arg NODE_ENV=testing --build-arg HUSKY_SKIP_INSTALL=true
      - run:
          name: Running docker container
          command: docker run blockade-api
      - run:
          name: Running linting for source code
          command: docker run -it blockade-api npm "run" "lint"
      - run:
          name: Running linting for markdown files
          command: docker run -it blockade-api npm "run" "lint-md"
  test:
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build image from Dockerfile
          command: docker build . --tag=blockade-api --build-arg NODE_ENV=testing --build-arg HUSKY_SKIP_INSTALL=true
      - run:
          name: Running automated test cases
          command: docker run -it blockade-api npm "run" "test"
workflows:
  version: 2
  build_test_lint:
    jobs:
      - lint
      - test
